export default `/// <reference path="./.sst/platform/config.d.ts" />

// Generated by easy-aws-deploy.
// Docs: https://ion.sst.dev
//
// Note: sst.config.ts is validated by \`sst deploy\` (which runs its own typecheck against SST's
// bundled platform definitions). The workspace \`pnpm typecheck\` skips this package intentionally
// — running tsc against SST's vendored .sst/platform internals conflicts with strict
// tsconfig settings (verbatimModuleSyntax, noImplicitOverride), and it's upstream code we don't own.
//
// TWO-PASS DEPLOY: First \`sst deploy\` emits editorUrl in outputs. Set {{PROJECT_NAME_UPPER}}_EDITOR_URL
// to that value and re-deploy to wire Cognito's callback URL for the PKCE flow to work.

export default \$config({
  app(input) {
    return {
      name: '{{PROJECT_NAME}}',
      removal: input?.stage === 'prod' ? 'retain' : 'remove',
      protect: input?.stage === 'prod',
      home: 'aws',
      providers: {
        aws: {
          region: '{{AWS_REGION}}',
          // Local dev: export AWS_PROFILE={{PROJECT_NAME}}-dev
          // CI: leave unset; credentials come from the OIDC-assumed github-actions-deployer role.
          ...(process.env.AWS_PROFILE ? { profile: process.env.AWS_PROFILE } : {}),
        },
      },
    };
  },
  async run() {
    // {{#if ENABLE_MULTI_TENANCY}}
    // Single-table DynamoDB — all tenants share one table, isolated by pk: TENANT#<id>.
    // Streams stay off: audit writes are explicit API calls, not stream processors.
    // GSI1 supports host→tenant lookups (gsi1pk: HOST#<domain>, gsi1sk: TENANT#<id>).
    const table = new sst.aws.Dynamo('{{PROJECT_NAME}}-prod', {
      fields: {
        pk: 'string',
        sk: 'string',
        gsi1pk: 'string',
        gsi1sk: 'string',
      },
      primaryIndex: { hashKey: 'pk', rangeKey: 'sk' },
      globalIndexes: {
        GSI1: {
          hashKey: 'gsi1pk',
          rangeKey: 'gsi1sk',
          projection: 'all',
        },
      },
      transform: {
        table: {
          // Point-in-time recovery: enables restore to any second in the last 35 days.
          pointInTimeRecovery: { enabled: true },
        },
      },
    });
    // {{/if ENABLE_MULTI_TENANCY}}

    // {{#if HAS_CLOUD_FRONT}}
    // S3 buckets — public access blocked by SST default. CloudFront OAC handles reads.
    const mediaBucket = new sst.aws.Bucket('{{PROJECT_NAME}}-media', {
      versioning: true,
    });
    const assetsBucket = new sst.aws.Bucket('{{PROJECT_NAME}}-assets', {
      versioning: true,
    });
    // {{/if HAS_CLOUD_FRONT}}

    // {{#if HAS_COGNITO}}
    // Cognito user pool — email-based auth, strong password policy, optional TOTP MFA.
    // Hosted UI custom domain (e.g. auth.your-agency.com) is deferred until a domain is
    // registered — for now we use Cognito's default prefix domain.
    const userPool = new sst.aws.CognitoUserPool('{{PROJECT_NAME}}-users', {
      usernames: ['email'],
      transform: {
        userPool: {
          passwordPolicy: {
            minimumLength: 12,
            requireLowercase: true,
            requireUppercase: true,
            requireNumbers: true,
            requireSymbols: true,
          },
          mfaConfiguration: 'OPTIONAL',
          softwareTokenMfaConfiguration: { enabled: true },
        },
      },
    });

    const accountId = aws.getCallerIdentityOutput({}).accountId;

    const userPoolDomain = new aws.cognito.UserPoolDomain(
      '{{PROJECT_NAME}}-userpool-domain',
      {
        domain: \$interpolate\`{{PROJECT_NAME}}-\${\$app.stage}-\${accountId}\`,
        userPoolId: userPool.id,
      },
    );

    // See TWO-PASS DEPLOY comment at the top of this file.
    const callbackUrl = process.env.{{PROJECT_NAME_UPPER}}_EDITOR_URL ?? 'https://localhost/';

    const editorClient = new aws.cognito.UserPoolClient('{{PROJECT_NAME}}-editor-client', {
      userPoolId: userPool.id,
      name: \$interpolate\`{{PROJECT_NAME}}-\${\$app.stage}-editor\`,
      generateSecret: false,
      explicitAuthFlows: ['ALLOW_USER_SRP_AUTH', 'ALLOW_REFRESH_TOKEN_AUTH'],
      allowedOauthFlows: ['code'],
      allowedOauthFlowsUserPoolClient: true,
      allowedOauthScopes: ['openid', 'email', 'profile'],
      callbackUrls: [callbackUrl],
      logoutUrls: [callbackUrl],
      supportedIdentityProviders: ['COGNITO'],
      preventUserExistenceErrors: 'ENABLED',
      accessTokenValidity: 60,
      idTokenValidity: 60,
      refreshTokenValidity: 30,
      tokenValidityUnits: {
        accessToken: 'minutes',
        idToken: 'minutes',
        refreshToken: 'days',
      },
    });

    const editorSite = new sst.aws.StaticSite('{{PROJECT_NAME}}-editor-spa', {
      path: '../../apps/editor',
      build: {
        command: 'pnpm build',
        output: 'dist',
      },
      environment: {
        PUBLIC_COGNITO_DOMAIN: \$interpolate\`\${userPoolDomain.domain}.auth.{{AWS_REGION}}.amazoncognito.com\`,
        PUBLIC_COGNITO_CLIENT_ID: editorClient.id,
        PUBLIC_AWS_REGION: '{{AWS_REGION}}',
      },
    });
    // {{/if HAS_COGNITO}}

    // {{#if HAS_KMS_AUTH}}
    // KMS asymmetric key for short-lived editor JWTs (see packages/server/src/auth/kms-jwt.ts).
    //
    // WHY KMS instead of a static secret:
    //   The inline editor runs on the TENANT's domain (e.g. client.com), not the editor SPA
    //   domain. Cognito can't issue tokens across origins. KMS lets us mint short-lived tokens
    //   (5-min site-edit, 10-min overlay) that the API can verify without sharing a secret.
    //
    // RSA_2048: smallest key size accepted for SIGN_VERIFY usage; matches API Gateway JWT
    //   authorizer expectations if we ever route overlay JWTs through it.
    // enableKeyRotation: false — KMS doesn't support automatic rotation for asymmetric keys.
    //   Rotate by creating a new key and updating the alias.
    const editorJwtKey = new aws.kms.Key('{{PROJECT_NAME}}-editor-jwt', {
      description: 'Signs short-lived editor session JWTs.',
      keyUsage: 'SIGN_VERIFY',
      customerMasterKeySpec: 'RSA_2048',
      enableKeyRotation: false,
    });
    new aws.kms.Alias('{{PROJECT_NAME}}-editor-jwt-alias', {
      name: \$interpolate\`alias/{{PROJECT_NAME}}-\${\$app.stage}-editor-jwt\`,
      targetKeyId: editorJwtKey.keyId,
    });
    // {{/if HAS_KMS_AUTH}}

    // === API Gateway ===
    // {{#if HAS_COGNITO}}
    // Declared before web so web can reference api.url in its environment.
    const api = new sst.aws.ApiGatewayV2('{{PROJECT_NAME}}-api', {
      cors: {
        allowMethods: ['*'],
        allowHeaders: ['Authorization', 'Content-Type', 'X-{{PROJECT_NAME_UPPER}}-Tenant'],
        allowOrigins: ['*'],
        allowCredentials: false,
        maxAge: '24 hours',
      },
    });
    // {{/if HAS_COGNITO}}

    // === SSR Lambda ===
    // {{#if ENABLE_MULTI_TENANCY}}
    const web = new sst.aws.Astro('{{PROJECT_NAME}}-web', {
      path: '../../apps/web',
      permissions: [
        // Read content + tenant config. SSR Lambda is read-only per spec — no write IAM here.
        {
          actions: ['dynamodb:GetItem', 'dynamodb:Query', 'dynamodb:BatchGetItem'],
          resources: [table.arn, \$interpolate\`\${table.arn}/index/*\`],
        },
        // Write SESSION#* items only (auth bridge cookie sessions).
        // App-level code enforces the SESSION# prefix; IAM condition scoping via LeadingKeys
        // is wired in a follow-up once sst.aws.Function supports condition keys on DDB actions.
        {
          actions: ['dynamodb:PutItem', 'dynamodb:DeleteItem'],
          resources: [table.arn],
        },
        // {{#if HAS_KMS_AUTH}}
        // Verify site-edit JWTs; sign 10-min overlay tokens per render.
        {
          actions: ['kms:Sign', 'kms:GetPublicKey', 'kms:Verify'],
          resources: [editorJwtKey.arn],
        },
        // {{/if HAS_KMS_AUTH}}
      ],
      environment: {
        {{PROJECT_NAME_UPPER}}_TABLE_NAME: table.name,
        {{PROJECT_NAME_UPPER}}_DEFAULT_TENANT_ID: 'default',
        // {{#if HAS_KMS_AUTH}}
        {{PROJECT_NAME_UPPER}}_EDITOR_JWT_KEY_ID: editorJwtKey.keyId,
        // {{/if HAS_KMS_AUTH}}
        // {{#if HAS_COGNITO}}
        {{PROJECT_NAME_UPPER}}_API_URL: api.url,
        // {{/if HAS_COGNITO}}
      },
    });
    // {{/if ENABLE_MULTI_TENANCY}}

    // === Editor API Lambda ===
    // {{#if HAS_COGNITO}}
    const apiHandler = new sst.aws.Function('{{PROJECT_NAME}}-api-handler', {
      handler: '../../packages/server/src/api/handler.handler',
      // {{#if ENABLE_MULTI_TENANCY}}
      link: [table],
      // {{/if ENABLE_MULTI_TENANCY}}
      permissions: [
        // Invalidate CloudFront paths on publish. '*' is acceptable here — the only
        // CloudFront action granted is CreateInvalidation, scoped to a distribution we own.
        {
          actions: ['cloudfront:CreateInvalidation'],
          resources: ['*'],
        },
        // {{#if HAS_KMS_AUTH}}
        {
          actions: ['kms:GetPublicKey', 'kms:Verify'],
          resources: [editorJwtKey.arn],
        },
        {
          actions: ['kms:Sign'],
          resources: [editorJwtKey.arn],
        },
        // {{/if HAS_KMS_AUTH}}
      ],
      environment: {
        // {{#if ENABLE_MULTI_TENANCY}}
        {{PROJECT_NAME_UPPER}}_TABLE_NAME: table.name,
        // {{/if ENABLE_MULTI_TENANCY}}
        // {{#if HAS_KMS_AUTH}}
        {{PROJECT_NAME_UPPER}}_EDITOR_JWT_KEY_ID: editorJwtKey.keyId,
        // {{/if HAS_KMS_AUTH}}
        {{PROJECT_NAME_UPPER}}_USER_POOL_ID: userPool.id,
        {{PROJECT_NAME_UPPER}}_COGNITO_CLIENT_ID: editorClient.id,
        // {{#if ENABLE_MULTI_TENANCY}}
        {{PROJECT_NAME_UPPER}}_WEB_DISTRIBUTION_ID: web.nodes.cdn.nodes.distribution.id,
        // {{/if ENABLE_MULTI_TENANCY}}
      },
    });

    // Cognito JWT authorizer — gates SPA-only routes (/me, /editor/site-token).
    //
    // WHY /content/* has no authorizer here:
    //   API Gateway's built-in JWT authorizer accepts a single issuer.
    //   /content/* must accept BOTH Cognito tokens (SPA writes) AND KMS-signed overlay tokens
    //   (inline editor writes, issued by SSR Lambda at render time). Two issuers = in-handler auth.
    const cognitoAuth = api.addAuthorizer({
      name: 'cognito',
      jwt: {
        issuer: \$interpolate\`https://cognito-idp.{{AWS_REGION}}.amazonaws.com/\${userPool.id}\`,
        audiences: [editorClient.id],
      },
    });

    const auth = { jwt: { authorizer: cognitoAuth.id } };

    api.route('GET /health', apiHandler.arn);
    api.route('GET /me', apiHandler.arn, { auth });
    api.route('POST /editor/site-token', apiHandler.arn, { auth });
    // No API-Gateway authorizer on /content/* — handler verifies both token types internally.
    api.route('ANY /content/{proxy+}', apiHandler.arn);
    // {{/if HAS_COGNITO}}

    return {
      // {{#if ENABLE_MULTI_TENANCY}}
      tableName: table.name,
      mediaBucketName: mediaBucket.name,
      assetsBucketName: assetsBucket.name,
      // {{/if ENABLE_MULTI_TENANCY}}
      // {{#if HAS_COGNITO}}
      userPoolId: userPool.id,
      cognitoDomain: \$interpolate\`\${userPoolDomain.domain}.auth.{{AWS_REGION}}.amazoncognito.com\`,
      cognitoClientId: editorClient.id,
      editorUrl: editorSite.url,
      apiUrl: api.url,
      webUrl: web.url,
      // {{/if HAS_COGNITO}}
    };
  },
});
`;
